name: provider
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  intl: ^0.16.0
  google_maps_flutter: ^0.5.27+1
  location: ^2.3.5
  http: ^0.12.0+2

  font_awesome_flutter: ^8.4.0
  flutter_spinkit: ^4.0.0
  flutter_rating_bar: ^3.0.0
  intro_views_flutter: ^2.6.0
  pin_code_text_field: 1.4.0
  image_picker: ^0.6.1+4
  geolocator: ^5.0.3
  sliding_up_panel: ^0.3.5
  flutter_calendar_carousel: ^1.3.28
  material_design_icons_flutter: ^3.2.3695
  flutter_tindercard: ^0.1.8
  dio: ^3.0.0
  progress_dialog: ^1.2.4
  json_annotation: ^3.0.0
  flutter_html: ^0.11.0
  shimmer: ^1.0.1
  flutter_slidable: ^0.5.3
  cached_network_image: ^2.2.0+1
  fl_chart: ^0.1.5
  flutter_compass: ^0.3.2
  cloud_firestore: ^0.13.5
  firebase_database: ^3.0.7
  firebase_auth: ^0.14.0+5
  shared_preferences: ^0.5.3+4
  share: ^0.6.5+2
  firebase_storage: ^3.0.8
  fluttertoast: ^3.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.1
  json_serializable: ^3.2.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/image/
    - assets/image/icon/
    - assets/style/
    - assets/image/directions/
    - lang/en.json
    - lang/ar.json

  fonts:
    - family: MYRIADPRO
      fonts:
        - asset: assets/fonts/MYRIADPRO-REGULAR.OTF
        - asset: assets/fonts/MYRIADPRO-SEMIBOLD.OTF
        - asset: assets/fonts/MYRIADPRO-BOLD.OTF
        - asset: assets/fonts/MYRIADPRO-SEMIBOLD.OTF
        - asset: assets/fonts/MYRIADPRO-COND.OTF
        - asset: assets/fonts/MYRIADPRO-CONDIT.OTF
        - asset: assets/fonts/MyriadPro-Light.otf

    - family: Avenir
      fonts:
          - asset: assets/avenor.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
#name: provider
#description: A new Flutter application.
#
## The following defines the version and build number for your application.
## A version number is three numbers separated by dots, like 1.2.43
## followed by an optional build number separated by a +.
## Both the version and the builder number may be overridden in flutter
## build by specifying --build-name and --build-number, respectively.
## In Android, build-name is used as versionName while build-number used as versionCode.
## Read more about Android versioning at https://developer.android.com/studio/publish/versioning
## In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
## Read more about iOS versioning at
## https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#version: 1.0.0+1
#
#environment:
#  sdk: ">=2.1.0 <3.0.0"
#
#dependencies:
#  flutter:
#    sdk: flutter
#  flutter_localizations:
#    sdk: flutter
#  flutter_cupertino_localizations: ^1.0.1
#  # The following adds the Cupertino Icons font to your application.
#  # Use with the CupertinoIcons class for iOS style icons.
#  cupertino_icons: ^0.1.2
#  intl: ^0.16.0
#  google_maps_flutter: ^0.5.27+1
#  location: ^2.3.5
#  http: ^0.12.0+2
#  font_awesome_flutter: ^8.4.0
#  flutter_spinkit: ^4.0.0
#  flutter_rating_bar: ^3.0.0
#  intro_views_flutter: ^2.6.0
#  pin_code_text_field: 1.4.0
#  image_picker: ^0.6.1+4
#  geolocator: ^5.0.3
#  sliding_up_panel: ^0.3.5
#  flutter_calendar_carousel: ^1.3.28
#  material_design_icons_flutter: ^3.2.3695
#  flutter_tindercard: ^0.1.8
#  dio: ^3.0.0
#  progress_dialog: ^1.2.4
#  json_annotation: ^3.0.0
#  flutter_html: ^0.11.0
#  shimmer: ^1.0.1
#  flutter_slidable: ^0.5.3
#  cached_network_image: ^2.2.0+1
#  fl_chart: ^0.1.5
#  flutter_compass: ^0.3.2
#  cloud_firestore: ^0.13.5
#  firebase_database: ^3.0.7
#  firebase_auth: ^0.14.0+5
#  shared_preferences: ^0.5.3+4
#  share: ^0.6.5+1
#  firebase_storage: ^3.0.8
#  fluttertoast: ^3.1.3
#
#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  build_runner: ^1.7.1
#  json_serializable: ^3.2.2
#
## For information on the generic Dart part of this file, see the
## following page: https://dart.dev/tools/pub/pubspec
#
## The following section is specific to Flutter.
#flutter:
#
#  # The following line ensures that the Material Icons font is
#  # included with your application, so that you can use the icons in
#  # the material Icons class.
#  uses-material-design: true
#  assets:
#    - assets/image/
#    - assets/image/icon/
#    - assets/style/
#    - assets/image/directions/
#    - lang/en.json
#    - lang/ar.json
#
#  fonts:
#    - family: MYRIADPRO
#      fonts:
#        - asset: assets/fonts/MYRIADPRO-REGULAR.OTF
#        - asset: assets/fonts/MYRIADPRO-SEMIBOLD.OTF
#        - asset: assets/fonts/MYRIADPRO-BOLD.OTF
#        - asset: assets/fonts/MYRIADPRO-SEMIBOLD.OTF
#        - asset: assets/fonts/MYRIADPRO-COND.OTF
#        - asset: assets/fonts/MYRIADPRO-CONDIT.OTF
#        - asset: assets/fonts/MyriadPro-Light.otf
#  # To add assets to your application, add an assets section, like this:
#  # assets:
#  #  - images/a_dot_burr.jpeg
#  #  - images/a_dot_ham.jpeg
#
#  # An image asset can refer to one or more resolution-specific "variants", see
#  # https://flutter.dev/assets-and-images/#resolution-aware.
#
#  # For details regarding adding assets from package dependencies, see
#  # https://flutter.dev/assets-and-images/#from-packages
#
#  # To add custom fonts to your application, add a fonts section here,
#  # in this "flutter" section. Each entry in this list should have a
#  # "family" key with the font family name, and a "fonts" key with a
#  # list giving the asset and other descriptors for the font. For
#  # example:
#  # fonts:
#  #   - family: Schyler
#  #     fonts:
#  #       - asset: fonts/Schyler-Regular.ttf
#  #       - asset: fonts/Schyler-Italic.ttf
#  #         style: italic
#  #   - family: Trajan Pro
#  #     fonts:
#  #       - asset: fonts/TrajanPro.ttf
#  #       - asset: fonts/TrajanPro_Bold.ttf
#  #         weight: 700
#  #
#  # For details regarding fonts from package dependencies,
#  # see https://flutter.dev/custom-fonts/#from-packages
